system(['wsl source enc_dec_ppm_1x64111.sh ','bar']);
eva('bar');
system(['wsl source enc_dec_ppm_1x64111.sh ','bottle']);
eva('bottle');
system(['wsl source enc_dec_ppm_1x64111.sh ','building']);
eva('building');
system(['wsl source enc_dec_ppm_1x64111.sh ','camera']);
eva('camera');
system(['wsl source enc_dec_ppm_1x64111.sh ','character']);
eva('character');
system(['wsl source enc_dec_ppm_1x64111.sh ','earth']);
eva('earth');
system(['wsl source enc_dec_ppm_1x64111.sh ','flower']);
eva('flower');
system(['wsl source enc_dec_ppm_1x64111.sh ','kitchen']);
eva('kitchen');
system(['wsl source enc_dec_ppm_1x64111.sh ','lemon']);
eva('lemon');
system(['wsl source enc_dec_ppm_1x64111.sh ','pc_desktop']);
eva('pc_desktop');
system(['wsl source enc_dec_ppm_1x64111.sh ','pcgame']);
eva('pcgame');
system(['wsl source enc_dec_ppm_1x64111.sh ','rainier']);
eva('rainier');
system(['wsl source enc_dec_ppm_1x64111.sh ','room']);
eva('room');
system(['wsl source enc_dec_ppm_1x64111.sh ','shop']);
eva('shop');
system(['wsl source enc_dec_ppm_1x64111.sh ','street']);
eva('street');
system(['wsl source enc_dec_ppm_1x64111.sh ','tatemono']);
eva('tatemono');
system(['wsl source enc_dec_ppm_1x64111.sh ','deskchair']);
eva('deskchair');
system(['wsl source enc_dec_ppm_1x64111.sh ','wedding']);
eva('wedding');

